"""
imageTool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdRvbDKxcoGcRcVS2hNUcGNwHKDiLOPm
"""
# gradio 설치
!pip install gradio -q

# OpenCV, numpy, gradio 임포트
import cv2
import numpy as np
import gradio as gr

# 기본 보정 필터
def adjust_basic(image, brightness, contrast, saturation, hue):
    """밝기/대비/채도/색조 통합 조정"""
    if image is None:
        return None
    img = image.astype(np.float32)

    # 대비(alpha) + 밝기(beta)
    # output = alpha * input + beta
    img = img * contrast + brightness
    img = np.clip(img, 0, 255).astype(np.uint8)

    # 채도/색조는 HSV 공간에서 조정
    if saturation != 1.0 or hue != 0:
        hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV).astype(np.float32)
        # H: 0~179 (OpenCV 기준)
        hsv[..., 0] = (hsv[..., 0] + hue) % 180
        # S: 0~255
        hsv[..., 1] = np.clip(hsv[..., 1] * saturation, 0, 255)
        hsv = hsv.astype(np.uint8)
        img = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)

    return img


def adjust_rgb(image, r_gain, g_gain, b_gain):
    """RGB 채널별 게인 조정 (컬러 그레이딩 느낌)"""
    if image is None:
        return None
    img = image.astype(np.float32)
    img[..., 0] *= r_gain
    img[..., 1] *= g_gain
    img[..., 2] *= b_gain
    return np.clip(img, 0, 255).astype(np.uint8)

# 블러 & 샤프닝
def apply_blur(image, blur_type, ksize):
    """여러 종류의 블러"""
    if image is None:
        return None
    # 커널 크기는 홀수여야 함
    ksize = max(1, int(ksize))
    if ksize % 2 == 0:
        ksize += 1

    if blur_type == "Gaussian (가우시안)":
        return cv2.GaussianBlur(image, (ksize, ksize), 0)
    elif blur_type == "Median (미디안)":
        return cv2.medianBlur(image, ksize)
    elif blur_type == "Bilateral (양방향)":
        # 경계는 살리면서 노이즈만 제거
        return cv2.bilateralFilter(image, ksize, 75, 75)
    else:  # Box (박스)
        return cv2.blur(image, (ksize, ksize))


def apply_sharpen(image, amount):
    """언샤프 마스크 방식 샤프닝"""
    if image is None:
        return None
    blurred = cv2.GaussianBlur(image, (0, 0), sigmaX=3)
    # original + amount * (original - blurred)
    sharpened = cv2.addWeighted(image, 1 + amount, blurred, -amount, 0)
    return np.clip(sharpened, 0, 255).astype(np.uint8)

# 엣지 검출
def apply_edge(image, method, threshold1, threshold2):
    """엣지 검출 (Canny / Sobel / Laplacian)"""
    if image is None:
        return None
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

    if method == "Canny":
        edges = cv2.Canny(gray, threshold1, threshold2)
    elif method == "Sobel":
        sx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
        sy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
        edges = np.sqrt(sx ** 2 + sy ** 2)
        edges = np.clip(edges, 0, 255).astype(np.uint8)
    else:  # Laplacian
        lap = cv2.Laplacian(gray, cv2.CV_64F, ksize=3)
        edges = np.clip(np.abs(lap), 0, 255).astype(np.uint8)

    # 3채널로 변환해서 반환 (보기 편하게)
    return cv2.cvtColor(edges, cv2.COLOR_GRAY2RGB)

# 스타일 필터
def apply_style(image, style):
    """여러 스타일 필터"""
    if image is None:
        return None

    if style == "Grayscale (흑백)":
        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)

    elif style == "Sepia (세피아)":
        # 세피아 변환 행렬
        kernel = np.array([
            [0.393, 0.769, 0.189],
            [0.349, 0.686, 0.168],
            [0.272, 0.534, 0.131],
        ])
        sepia = cv2.transform(image, kernel)
        return np.clip(sepia, 0, 255).astype(np.uint8)

    elif style == "Invert (반전)":
        return 255 - image

    elif style == "Cartoon (카툰)":
        # 1) 색상은 단순화: bilateral filter로 색 영역을 평탄화
        color = image
        for _ in range(2):
            color = cv2.bilateralFilter(color, d=9, sigmaColor=75, sigmaSpace=75)
        # 2) 윤곽선 추출
        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        gray_blur = cv2.medianBlur(gray, 7)
        edges = cv2.adaptiveThreshold(
            gray_blur, 255,
            cv2.ADAPTIVE_THRESH_MEAN_C,
            cv2.THRESH_BINARY,
            blockSize=9, C=2,
        )
        edges_rgb = cv2.cvtColor(edges, cv2.COLOR_GRAY2RGB)
        # 3) 색과 윤곽선 합성
        return cv2.bitwise_and(color, edges_rgb)

    elif style == "Pencil Sketch (연필 스케치)":
        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        inv = 255 - gray
        blur = cv2.GaussianBlur(inv, (21, 21), 0)
        # color dodge
        sketch = cv2.divide(gray, 255 - blur, scale=256)
        return cv2.cvtColor(sketch, cv2.COLOR_GRAY2RGB)

    elif style == "Oil Painting (유화 느낌)":
        # stylization은 OpenCV에 내장된 NPR(Non-Photorealistic Rendering) 함수
        bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        styl = cv2.stylization(bgr, sigma_s=60, sigma_r=0.45)
        return cv2.cvtColor(styl, cv2.COLOR_BGR2RGB)

    else:
        return image


def apply_pixelate(image, pixel_size):
    """픽셀화(모자이크)"""
    if image is None:
        return None
    h, w = image.shape[:2]
    pixel_size = max(1, int(pixel_size))
    # 작게 축소했다가 다시 키우면 모자이크 효과
    small = cv2.resize(
        image, (max(1, w // pixel_size), max(1, h // pixel_size)),
        interpolation=cv2.INTER_LINEAR,
    )
    return cv2.resize(small, (w, h), interpolation=cv2.INTER_NEAREST)


print("필터 함수 로드 완료")

with gr.Blocks(title="이미지 필터 앱", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 이미지 필터 앱")
    gr.Markdown("OpenCV + NumPy + Gradio로 만든 이미지 필터 도구입니다. 좌측에 이미지를 올리고 슬라이더를 조정해보세요.")

    with gr.Tabs():
        # ---------- 탭 1: 기본 보정 ----------
        with gr.Tab("기본 보정"):
            with gr.Row():
                with gr.Column():
                    img_in1 = gr.Image(label="입력 이미지", type="numpy")
                    brightness = gr.Slider(-100, 100, value=0, step=1, label="밝기 (Brightness)")
                    contrast = gr.Slider(0.0, 3.0, value=1.0, step=0.05, label="대비 (Contrast)")
                    saturation = gr.Slider(0.0, 3.0, value=1.0, step=0.05, label="채도 (Saturation)")
                    hue = gr.Slider(-90, 90, value=0, step=1, label="색조 (Hue shift)")
                with gr.Column():
                    img_out1 = gr.Image(label="결과")

            for ctrl in [brightness, contrast, saturation, hue]:
                ctrl.change(
                    adjust_basic,
                    inputs=[img_in1, brightness, contrast, saturation, hue],
                    outputs=img_out1,
                )
            img_in1.change(
                adjust_basic,
                inputs=[img_in1, brightness, contrast, saturation, hue],
                outputs=img_out1,
            )

        # ---------- 탭 2: RGB 채널 ----------
        with gr.Tab("RGB 채널"):
            with gr.Row():
                with gr.Column():
                    img_in2 = gr.Image(label="입력 이미지", type="numpy")
                    r_gain = gr.Slider(0.0, 2.0, value=1.0, step=0.05, label="R")
                    g_gain = gr.Slider(0.0, 2.0, value=1.0, step=0.05, label="G")
                    b_gain = gr.Slider(0.0, 2.0, value=1.0, step=0.05, label="B")
                with gr.Column():
                    img_out2 = gr.Image(label="결과")

            for ctrl in [r_gain, g_gain, b_gain, img_in2]:
                ctrl.change(
                    adjust_rgb,
                    inputs=[img_in2, r_gain, g_gain, b_gain],
                    outputs=img_out2,
                )

        # ---------- 탭 3: 블러 & 샤프닝 ----------
        with gr.Tab("블러 / 샤프닝"):
            with gr.Row():
                with gr.Column():
                    img_in3 = gr.Image(label="입력 이미지", type="numpy")
                    blur_type = gr.Dropdown(
                        ["Gaussian (가우시안)", "Median (미디안)", "Bilateral (양방향)", "Box (박스)"],
                        value="Gaussian (가우시안)",
                        label="블러 종류",
                    )
                    ksize = gr.Slider(1, 51, value=5, step=2, label="커널 크기 (홀수)")
                    btn_blur = gr.Button("블러 적용")
                    gr.Markdown("---")
                    sharpen_amt = gr.Slider(0.0, 5.0, value=1.0, step=0.1, label="샤프닝 강도")
                    btn_sharp = gr.Button("샤프닝 적용")
                with gr.Column():
                    img_out3 = gr.Image(label="결과")

            btn_blur.click(apply_blur, [img_in3, blur_type, ksize], img_out3)
            btn_sharp.click(apply_sharpen, [img_in3, sharpen_amt], img_out3)

        # ---------- 탭 4: 엣지 검출 ----------
        with gr.Tab("엣지 검출"):
            with gr.Row():
                with gr.Column():
                    img_in4 = gr.Image(label="입력 이미지", type="numpy")
                    edge_method = gr.Dropdown(
                        ["Canny", "Sobel", "Laplacian"],
                        value="Canny",
                        label="방법",
                    )
                    th1 = gr.Slider(0, 255, value=100, step=1, label="Threshold 1 (Canny만)")
                    th2 = gr.Slider(0, 255, value=200, step=1, label="Threshold 2 (Canny만)")
                with gr.Column():
                    img_out4 = gr.Image(label="결과")

            for ctrl in [edge_method, th1, th2, img_in4]:
                ctrl.change(apply_edge, [img_in4, edge_method, th1, th2], img_out4)

        # ---------- 탭 5: 스타일 ----------
        with gr.Tab("스타일 필터"):
            with gr.Row():
                with gr.Column():
                    img_in5 = gr.Image(label="입력 이미지", type="numpy")
                    style = gr.Radio(
                        [
                            "Grayscale (흑백)",
                            "Sepia (세피아)",
                            "Invert (반전)",
                            "Cartoon (카툰)",
                            "Pencil Sketch (연필 스케치)",
                            "Oil Painting (유화 느낌)",
                        ],
                        value="Cartoon (카툰)",
                        label="스타일",
                    )
                with gr.Column():
                    img_out5 = gr.Image(label="결과")

            for ctrl in [style, img_in5]:
                ctrl.change(apply_style, [img_in5, style], img_out5)

        # ---------- 탭 6: 픽셀화 ----------
        with gr.Tab("픽셀화"):
            with gr.Row():
                with gr.Column():
                    img_in6 = gr.Image(label="입력 이미지", type="numpy")
                    pixel_size = gr.Slider(2, 50, value=10, step=1, label="픽셀 크기")
                with gr.Column():
                    img_out6 = gr.Image(label="결과")

            for ctrl in [pixel_size, img_in6]:
                ctrl.change(apply_pixelate, [img_in6, pixel_size], img_out6)

print("인터페이스 구성 완료")

demo.launch(share=True, debug=False)
